import java.util.TreeMap;

public class DivisasEnEspanol {
    TreeMap<String, String> diccionario;
    public DivisasEnEspanol() {
        // Crear un TreeMap para almacenar las claves y valores
        TreeMap<String, String> diccionario = new TreeMap<>();

        // Claves y valores
        String[] claves = {
                "Dirham",
                "Afghani afgano",
                "Lek albanés",
                "Dram armenio",
                "Florín de las Antillas Neerlandesas",
                "Kwanza angoleño",
                "Peso argentino",
                "Dólar australiano",
                "Florín de Aruba",
                "Manat azerbaiyano",
                "Marco convertible de Bosnia y Herzegovina",
                "Dólar de Barbados",
                "Taka bangladesí",
                "Lev búlgaro",
                "Dinar bareiní",
                "Franco burundés",
                "Dólar de las Bermudas",
                "Dólar de Brunéi",
                "Boliviano boliviano",
                "Real brasileño",
                "Dólar de las Bahamas",
                "Bitcoin",
                "Ngultrum butanés",
                "Pula botsuano",
                "Rublo bielorruso",
                "Rublo bielorruso (moneda anterior)",
                "Dólar beliceño",
                "Dólar canadiense",
                "Franco congoleño",
                "Franco suizo",
                "Unidad de fomento chilena",
                "Peso chileno",
                "Yuan chino",
                "Peso colombiano",
                "Colón costarricense",
                "Peso cubano convertible",
                "Peso cubano",
                "Escudo caboverdiano",
                "Corona checa",
                "Franco yibutiano",
                "Corona danesa",
                "Peso dominicano",
                "Dinar argelino",
                "Libra egipcia",
                "Nakfa eritreo",
                "Birr etíope",
                "Euro",
                "Dólar fiyiano",
                "Libra de las Islas Malvinas",
                "Libra esterlina",
                "Lari georgiano",
                "Libra de Guernsey",
                "Cedi ghanés",
                "Libra de Gibraltar",
                "Dalasi gambiano",
                "Franco guineano",
                "Quetzal guatemalteco",
                "Dólar guyanés",
                "Dólar de Hong Kong",
                "Lempira hondureño",
                "Kuna croata",
                "Gourde haitiano",
                "Forint húngaro",
                "Rupia indonesia",
                "Nuevo séquel israelí",
                "Libra de la Isla de Man",
                "Rupia india",
                "Dinar iraquí",
                "Rial iraní",
                "Corona islandesa",
                "Libra de Jersey",
                "Dólar jamaicano",
                "Dinar jordano",
                "Yen japonés",
                "Chelín keniano",
                "Som kirguís",
                "Riel camboyano",
                "Franco comorense",
                "Won norcoreano",
                "Won surcoreano",
                "Dinar kuwaití",
                "Dólar de las Islas Caimán",
                "Tenge kazajo",
                "Kip laosiano",
                "Libra libanesa",
                "Rupia de Sri Lanka",
                "Dólar liberiano",
                "Loti lesothense",
                "Litas lituano",
                "Lats letón",
                "Dinar libio",
                "Dirham marroquí",
                "Leu moldavo",
                "Ariary malgache",
                "Denar macedonio",
                "Kyat birmano",
                "Tugrik mongol",
                "Pataca de Macao",
                "Ouguiya mauritana",
                "Rupia mauriciana",
                "Rufiyaa de Maldivas",
                "Kwacha malauí",
                "Peso mexicano",
                "Ringgit malayo",
                "Metical mozambiqueño",
                "Dólar namibio",
                "Naira nigeriano",
                "Córdoba nicaragüense",
                "Corona noruega",
                "Rupia nepalí",
                "Dólar neozelandés",
                "Rial omaní",
                "Balboa panameño",
                "Sol peruano",
                "Kina de Papúa Nueva Guinea",
                "Peso filipino",
                "Rupia pakistaní",
                "Złoty polaco",
                "Guaraní paraguayo",
                "Riyal qatarí",
                "Leu rumano",
                "Dinar serbio",
                "Rublo ruso",
                "Franco ruandés",
                "Riyal saudí",
                "Dólar de las Islas Salomón",
                "Rupia de Seychelles",
                "Libra sudanesa",
                "Corona sueca",
                "Dólar singapurense",
                "Libra de Santa Elena",
                "Leone de Sierra Leona",
                "Leone de Sierra Leona (moneda anterior)",
                "Chelín somalí",
                "Libra sursudanesa",
                "Dólar surinamés",
                "Dobra de Santo Tomé y Príncipe",
                "Libra siria",
                "Lilangeni suazi",
                "Baht tailandés",
                "Somoni tayiko",
                "Manat turcomano",
                "Dinar tunecino",
                "Pa'anga tongano",
                "Lira turca",
                "Dólar de Trinidad y Tobago",
                "Nuevo dólar taiwanés",
                "Chelín tanzano",
                "Grivna ucraniana",
                "Chelín ugandés",
                "Dólar estadounidense",
                "Peso uruguayo",
                "Som uzbeko",
                "Bolívar venezolano (moneda anterior)",
                "Bolívar soberano venezolano",
                "Dong vietnamita",
                "Vatu vanuatuense",
                "Tala samoano",
                "Franco CFA de África Central",
                "Plata (código ISO 4217)",
                "Oro (código ISO 4217)",
                "Dólar del Caribe Oriental",
                "Derechos especiales de giro (código ISO 4217)",
                "Franco CFA de África Occidental",
                "Franco CFP del Pacífico",
                "Rial yemení",
                "Rand sudafricano",
                "Kwacha zambiano (moneda anterior)",
                "Kwacha zambiano",
                "Dólar zimbabuense (moneda anterior)"
        };
        String[] valores = {
                "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BYR", "BZD", "CAD", "CDF", "CHF", "CLF", "CLP", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LTL", "LVL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SSP", "SRD", "STD", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VEF", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPF", "YER", "ZAR", "ZMK", "ZMW", "ZWL"
        };

        // Verificar que haya la misma cantidad de claves y valores
        if (claves.length == valores.length) {
            for (int i = 0; i < claves.length; i++) {
                diccionario.put(claves[i] + " (" + valores[i] + ")", valores[i]);
            }
        } else {
            System.out.println("La cantidad de claves y valores no coincide.");
        }

        this.diccionario = diccionario;
    }
}


