import java.util.TreeMap;

public class DivisasEnIngles {
    TreeMap<String, String> diccionario;
    public DivisasEnIngles() {
        // Crear un TreeMap para almacenar las claves y valores
        TreeMap<String, String> diccionario = new TreeMap<>();

        // Claves y valores
        String[] claves = {
                "Dirham",
                "Afghan Afghani",
                "Albanian Lek",
                "Armenian Dram",
                "Netherlands Antillean Guilder",
                "Angolan Kwanza",
                "Argentine Peso",
                "Australian Dollar",
                "Aruban Florin",
                "Azerbaijani Manat",
                "Bosnia and Herzegovina Convertible Mark",
                "Barbadian Dollar",
                "Bangladeshi Taka",
                "Bulgarian Lev",
                "Bahraini Dinar",
                "Burundian Franc",
                "Bermudian Dollar",
                "Brunei Dollar",
                "Bolivian Boliviano",
                "Brazilian Real",
                "Bahamian Dollar",
                "Bitcoin",
                "Bhutanese Ngultrum",
                "Botswanan Pula",
                "Belarusian Ruble",
                "Belarusian Ruble (Old Currency)",
                "Belize Dollar",
                "Canadian Dollar",
                "Congolese Franc",
                "Swiss Franc",
                "Chilean Unidad de Fomento",
                "Chilean Peso",
                "Chinese Yuan",
                "Colombian Peso",
                "Costa Rican Colón",
                "Cuban Convertible Peso",
                "Cuban Peso",
                "Cape Verdean Escudo",
                "Czech Koruna",
                "Djiboutian Franc",
                "Danish Krone",
                "Dominican Peso",
                "Algerian Dinar",
                "Egyptian Pound",
                "Eritrean Nakfa",
                "Ethiopian Birr",
                "Euro",
                "Fijian Dollar",
                "Falkland Islands Pound",
                "British Pound Sterling",
                "Georgian Lari",
                "Guernsey Pound",
                "Ghanaian Cedi",
                "Gibraltar Pound",
                "Gambian Dalasi",
                "Guinean Franc",
                "Guatemalan Quetzal",
                "Guyanese Dollar",
                "Hong Kong Dollar",
                "Honduran Lempira",
                "Croatian Kuna",
                "Haitian Gourde",
                "Hungarian Forint",
                "Indonesian Rupiah",
                "Israeli New Sheqel",
                "Isle of Man Pound",
                "Indian Rupee",
                "Iraqi Dinar",
                "Iranian Rial",
                "Icelandic Krona",
                "Jersey Pound",
                "Jamaican Dollar",
                "Jordanian Dinar",
                "Japanese Yen",
                "Kenyan Shilling",
                "Kyrgystani Som",
                "Cambodian Riel",
                "Comorian Franc",
                "North Korean Won",
                "South Korean Won",
                "Kuwaiti Dinar",
                "Cayman Islands Dollar",
                "Kazakhstani Tenge",
                "Laotian Kip",
                "Lebanese Pound",
                "Sri Lankan Rupee",
                "Liberian Dollar",
                "Lesotho Loti",
                "Lithuanian Litas",
                "Latvian Lats",
                "Libyan Dinar",
                "Moroccan Dirham",
                "Moldovan Leu",
                "Malagasy Ariary",
                "Macedonian Denar",
                "Burmese Kyat",
                "Mongolian Tugrik",
                "Macanese Pataca",
                "Mauritanian Ouguiya",
                "Mauritian Rupee",
                "Maldivian Rufiyaa",
                "Malawian Kwacha",
                "Mexican Peso",
                "Malaysian Ringgit",
                "Mozambican Metical",
                "Namibian Dollar",
                "Nigerian Naira",
                "Nicaraguan Córdoba",
                "Norwegian Krone",
                "Nepalese Rupee",
                "New Zealand Dollar",
                "Omani Rial",
                "Panamanian Balboa",
                "Peruvian Nuevo Sol",
                "Papua New Guinean Kina",
                "Philippine Peso",
                "Pakistani Rupee",
                "Polish Złoty",
                "Paraguayan Guarani",
                "Qatari Riyal",
                "Romanian Leu",
                "Serbian Dinar",
                "Russian Ruble",
                "Rwandan Franc",
                "Saudi Riyal",
                "Solomon Islands Dollar",
                "Seychellois Rupee",
                "Sudanese Pound",
                "Swedish Krona",
                "Singapore Dollar",
                "Saint Helena Pound",
                "Sierra Leonean Leone",
                "Sierra Leonean Leone (Old Currency)",
                "Somali Shilling",
                "South Sudanese Pound",
                "Surinamese Dollar",
                "São Tomé and Príncipe Dobra",
                "Syrian Pound",
                "Swazi Lilangeni",
                "Thai Baht",
                "Tajikistani Somoni",
                "Turkmenistani Manat",
                "Tunisian Dinar",
                "Tongan Pa'anga",
                "Turkish Lira",
                "Trinidad and Tobago Dollar",
                "New Taiwan Dollar",
                "Tanzanian Shilling",
                "Ukrainian Hryvnia",
                "Ugandan Shilling",
                "United States Dollar",
                "Uruguayan Peso",
                "Uzbekistan Som",
                "Venezuelan Bolivar (Old Currency)",
                "Venezuelan Bolívar Soberano",
                "Vietnamese Dong",
                "Vanuatu Vatu",
                "Samoan Tala",
                "Central African CFA Franc",
                "Silver (ISO 4217 Code)",
                "Gold (ISO 4217 Code)",
                "East Caribbean Dollar",
                "Special Drawing Rights (ISO 4217 Code)",
                "West African CFA Franc",
                "CFP Franc",
                "Yemeni Rial",
                "South African Rand",
                "Zambian Kwacha (Old Currency)",
                "Zambian Kwacha",
                "Zimbabwean Dollar (Old Currency)"
        };

        String[] valores = {
                "AED", "AFN", "ALL", "AMD", "ANG", "AOA", "ARS", "AUD", "AWG", "AZN", "BAM", "BBD", "BDT", "BGN", "BHD", "BIF", "BMD", "BND", "BOB", "BRL", "BSD", "BTC", "BTN", "BWP", "BYN", "BYR", "BZD", "CAD", "CDF", "CHF", "CLF", "CLP", "CNY", "COP", "CRC", "CUC", "CUP", "CVE", "CZK", "DJF", "DKK", "DOP", "DZD", "EGP", "ERN", "ETB", "EUR", "FJD", "FKP", "GBP", "GEL", "GGP", "GHS", "GIP", "GMD", "GNF", "GTQ", "GYD", "HKD", "HNL", "HRK", "HTG", "HUF", "IDR", "ILS", "IMP", "INR", "IQD", "IRR", "ISK", "JEP", "JMD", "JOD", "JPY", "KES", "KGS", "KHR", "KMF", "KPW", "KRW", "KWD", "KYD", "KZT", "LAK", "LBP", "LKR", "LRD", "LSL", "LTL", "LVL", "LYD", "MAD", "MDL", "MGA", "MKD", "MMK", "MNT", "MOP", "MRO", "MUR", "MVR", "MWK", "MXN", "MYR", "MZN", "NAD", "NGN", "NIO", "NOK", "NPR", "NZD", "OMR", "PAB", "PEN", "PGK", "PHP", "PKR", "PLN", "PYG", "QAR", "RON", "RSD", "RUB", "RWF", "SAR", "SBD", "SCR", "SDG", "SEK", "SGD", "SHP", "SLE", "SLL", "SOS", "SSP", "SRD", "STD", "SYP", "SZL", "THB", "TJS", "TMT", "TND", "TOP", "TRY", "TTD", "TWD", "TZS", "UAH", "UGX", "USD", "UYU", "UZS", "VEF", "VES", "VND", "VUV", "WST", "XAF", "XAG", "XAU", "XCD", "XDR", "XOF", "XPF", "YER", "ZAR", "ZMK", "ZMW", "ZWL"
        };

        // Verificar que haya la misma cantidad de claves y valores
        for (int i = 0; i < claves.length; i++) {
            diccionario.put(claves[i] + " (" + valores[i] + ")", valores[i]);
        }

        this.diccionario = diccionario;
    }
}



